apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
 name: otdd-handler
 namespace: istio-system
spec:
 adapter: otdd
 connection:
   address: "[::]:18764" #replaces at runtime by the test
 params:
   addr: "otddserver:18764"
---

# instance for template metric
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
 name: otdd-logentry
 namespace: istio-system
spec:
 template: logentry
 params:
   variables:
     testcase: otdd.testcase | ""
---

# rule to dispatch to handler h1
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: otdd-rule
 namespace: istio-system
spec:
 actions:
 - handler: otdd-handler.istio-system
   instances:
   - otdd-logentry
---
