apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: otdd-adapter
  namespace: otdd-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otdd-adapter
  template:
    metadata:
      labels:
        app: otdd-adapter
    spec:
      containers:
      - name: otdd-adapter
        image: "otdd/otdd-adapter:1.0.0-alpha.0"
---
apiVersion: v1
kind: Service
metadata:
  name: otdd-adapter
  namespace: otdd-system
  labels:
    app: otdd-adapter
spec:
  ports:
  - port: 35480
  selector:
    app: otdd-adapter
